import assert from 'node:assert/strict'
import { mkdir, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

// Reuse an existing Playwright installation; this prototype adds no package dependencies.
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright')
const output = resolve(process.env.ARTIFACT_DIR || '.pi/workspace-prototype/review')
await mkdir(output, { recursive: true })
const browser = await chromium.launch({ headless: true, channel: process.env.BROWSER_CHANNEL || 'chrome' })
const url = new URL('./workspace-plane.html', import.meta.url).href
const results = []
const errors = []
const record = (name) => results.push({ name, status: 'passed' })
const screenshot = (page, name) => process.env.CAPTURE === '0' ? Promise.resolve() : page.screenshot({ path: resolve(output, `${name}.png`), fullPage: true })
const noPageOverflow = async (page) => {
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), '页面不能横向溢出')
  assert.ok(await page.evaluate(() => document.documentElement.scrollHeight <= innerHeight), '窗口不能纵向溢出')
}

try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 960 }, reducedMotion: 'reduce' })
  page.on('pageerror', error => errors.push(error.message))
  page.on('request', request => {
    assert.ok(request.url().startsWith('file:'), `原型不应发出网络请求：${request.url()}`)
  })
  await page.goto(url)
  await noPageOverflow(page)
  assert.equal(await page.locator('.workspace-group').count(), 3)
  assert.equal(await page.locator('.session-row').count(), 6)
  assert.equal(await page.locator('.is-active .session-title').innerText(), '设计工作区侧栏')
  assert.ok(await page.getByText('交互原型 · 未连接 PTY', { exact: true }).isVisible())
  await screenshot(page, 'desktop')
  record('初始工作区分组、pi 内容、原型边界与窗口布局')

  await page.getByRole('button', { name: '在 website 新建会话', exact: true }).click()
  assert.equal(await page.locator('#tool-workspace').inputValue(), 'website')
  assert.match(await page.locator('#tool-cwd').innerText(), /website/)
  await screenshot(page, 'tool-picker')
  await page.locator('#tool-filter').fill('不存在的工具')
  assert.ok(await page.getByText('没有匹配工具，可在下方添加自定义命令。').isVisible())
  await page.keyboard.press('Escape')
  assert.equal(await page.locator('dialog[open]').count(), 0)
  record('上下文工具菜单、搜索空态、Escape 关闭')

  await page.locator('#terminal-input').fill('未提交的项目草稿')
  await page.locator('[data-action="activate-session"][data-session="git-main"]').click()
  assert.equal(await page.locator('.session-state').count(), 0)
  await page.locator('[data-action="git-file"][data-index="1"]').click()
  assert.match(await page.locator('.tui-diff').innerText(), /sessionIds/)
  await screenshot(page, 'lazygit')
  await page.locator('[data-action="activate-workspace"][data-workspace="website"]').click()
  assert.equal(await page.locator('#title-workspace').innerText(), 'website')
  await page.locator('[data-action="activate-workspace"][data-workspace="jagent"]').click()
  assert.equal(await page.locator('.is-active .session-title').innerText(), 'lazygit')
  await page.locator('[data-action="activate-session"][data-session="pi-main"]').click()
  assert.equal(await page.locator('#terminal-input').inputValue(), '未提交的项目草稿')
  await page.keyboard.press('Enter')
  assert.ok(await page.getByText(/原型不会调用模型/).isVisible())
  record('BEL 清除、工作区恢复上次会话、草稿保留与演示提交')

  await page.locator('[data-action="activate-session"][data-session="yazi-main"]').click()
  await page.locator('[data-action="yazi-file"][data-index="4"]').click()
  assert.match(await page.locator('.file-preview').innerText(), /一个工作区，多种终端工具/)
  await screenshot(page, 'yazi')
  await page.keyboard.press('ArrowUp')
  assert.match(await page.locator('.file-preview').innerText(), /workspace-plane\.html/)
  record('yazi 点击与键盘文件选择')

  await page.locator('[data-action="activate-session"][data-session="shell-main"]').click()
  await page.locator('#terminal-input').fill('pwd')
  await page.keyboard.press('Enter')
  assert.equal(await page.locator('.demo-reply').last().innerText(), '~/Projects/jagent-terminal')
  await page.locator('#terminal-input').fill('echo <script>alert("x")</script>')
  await page.keyboard.press('Enter')
  assert.equal(await page.locator('.demo-reply').last().innerText(), '<script>alert("x")</script>')
  assert.equal(await page.locator('#terminal-log script').count(), 0)
  await page.locator('#terminal-input').fill('clear')
  await page.keyboard.press('Enter')
  assert.equal(await page.locator('#terminal-log pre, #terminal-log .terminal-entry').count(), 0)
  await page.locator('#terminal-input').fill('组合输入')
  await page.locator('#terminal-input').dispatchEvent('keydown', { key: 'Enter', isComposing: true, bubbles: true })
  assert.equal(await page.locator('#terminal-input').inputValue(), '组合输入')
  await page.keyboard.press('Control+k')
  assert.equal(await page.locator('dialog[open]').count(), 0)
  record('Shell cwd、输入转义、IME Enter 与终端 Ctrl 键保留')

  await page.locator('[data-action="activate-workspace"][data-workspace="playground"]').click()
  assert.ok(await page.getByRole('heading', { name: 'playground', exact: true }).isVisible())
  await screenshot(page, 'empty-workspace')
  await page.getByRole('button', { name: '新建 pi 会话', exact: true }).click()
  assert.equal(await page.locator('#title-workspace').innerText(), 'playground')
  assert.match(await page.locator('.terminal-context').innerText(), /playground/)
  record('空工作区引导与快捷创建 pi')

  await page.getByRole('button', { name: '在 jagent-terminal 新建会话', exact: true }).click()
  await page.locator('#tool-filter').fill('btop')
  await page.keyboard.press('Enter')
  assert.equal(await page.locator('#title-workspace').innerText(), 'jagent-terminal')
  assert.ok(await page.getByText('静态示例 · 非真实监控', { exact: true }).isVisible())
  await screenshot(page, 'btop')
  record('过滤并用 Enter 创建工具，btop 系统级范围说明')

  await page.getByRole('button', { name: '添加工作区', exact: true }).click()
  await page.locator('#workspace-form button[type="submit"]').click()
  assert.equal(await page.locator('#workspace-form [aria-invalid="true"]').count(), 2)
  await page.locator('#workspace-name').fill('long-workspace-name-with-many-characters-测试项目')
  await page.locator('#workspace-path').fill('relative/path')
  await page.locator('#workspace-form button[type="submit"]').click()
  assert.match(await page.locator('#workspace-path-error').innerText(), /绝对路径/)
  await page.locator('#workspace-path').fill('C:\\Projects\\tool-playground')
  await page.locator('#workspace-form button[type="submit"]').click()
  await noPageOverflow(page)
  assert.equal(await page.locator('.workspace-group').count(), 4)
  await page.getByRole('button', { name: '选择其他工具', exact: false }).click()
  await page.getByRole('button', { name: /自定义命令.*运行任意/ }).click()
  await page.locator('#custom-form button[type="submit"]').click()
  assert.equal(await page.locator('#custom-form [aria-invalid="true"]').count(), 2)
  await page.locator('#custom-name').fill('nvim <示例>')
  await page.locator('#custom-command').fill('nvim . && echo "<demo>"')
  await page.locator('#custom-form button[type="submit"]').click()
  assert.match(await page.locator('.shell-log').innerText(), /nvim \. && echo "<demo>"/)
  assert.match(await page.locator('.terminal-context').innerText(), /C:\\Projects/)
  record('添加工作区、表单错误、Windows 路径、自定义命令与长名称')

  await page.locator('.session-row.is-active .session-more').click()
  await page.locator('#session-name').fill('重命名后的工具')
  await page.locator('#session-form button[type="submit"]').click()
  assert.equal(await page.locator('#title-session').innerText(), '重命名后的工具')
  await page.getByRole('button', { name: /搜索会话/ }).first().click()
  await page.locator('#session-search').fill('重命名后的工具')
  assert.equal(await page.locator('.search-result').count(), 1)
  await page.keyboard.press('Enter')
  assert.equal(await page.locator('#title-session').innerText(), '重命名后的工具')
  await page.locator('.session-row.is-active .session-more').click()
  await page.getByRole('button', { name: '移除示例会话', exact: true }).click()
  assert.ok(await page.getByRole('button', { name: '新建 pi 会话', exact: true }).isVisible())
  record('重命名、跨工作区搜索、移除最后会话后的空态')

  // Fresh pages are the canonical layout captures; no data from prior interactions leaks in.
  for (const [name, width, height] of [['compact', 1024, 768], ['mobile', 390, 844]]) {
    const view = await browser.newPage({ viewport: { width, height }, reducedMotion: 'reduce' })
    view.on('pageerror', error => errors.push(error.message))
    await view.goto(url)
    await noPageOverflow(view)
    await screenshot(view, name)
    if (name === 'mobile') {
      assert.equal(await view.locator('#sidebar-toggle').getAttribute('aria-expanded'), 'false')
      await view.locator('#sidebar-toggle').click()
      assert.ok(await view.locator('#workspace-drawer').isVisible())
      await screenshot(view, 'mobile-workspaces')
      await view.getByRole('button', { name: '在 website 新建会话', exact: true }).click()
      assert.equal(await view.locator('#workspace-drawer').isVisible(), false)
      assert.ok(await view.locator('#tool-dialog').isVisible())
      await view.locator('#tool-filter').fill('pi')
      await view.keyboard.press('Enter')
      assert.equal(await view.locator('#title-workspace').innerText(), 'website')
      assert.equal(await view.locator('dialog[open]').count(), 0)
      await noPageOverflow(view)
      await view.locator('#sidebar-toggle').click()
      await view.keyboard.press('Escape')
      assert.equal(await view.locator('#workspace-drawer').isVisible(), false)
      assert.equal(await view.locator('#sidebar-toggle').getAttribute('aria-expanded'), 'false')
    }
    await view.close()
  }
  record('1024px 紧凑布局、390px 抽屉、移动端创建与退出、减少动效')

  assert.deepEqual(errors, [], '不得存在浏览器运行时错误')
  const report = { file: fileURLToPath(new URL('./workspace-plane.html', import.meta.url)), results, browserErrors: errors }
  await writeFile(resolve(output, 'test-report.json'), JSON.stringify(report, null, 2))
  console.log(JSON.stringify(report, null, 2))
} finally {
  await browser.close()
}
