/* auto-generated by NAPI-RS */
/* eslint-disable */
/** The main GPUI renderer exposed to Node.js. */
export declare class GpuixRenderer {
  constructor(eventCallback?: (((err: Error | null, arg: EventPayload) => any)) | undefined | null)
  /** Initialize GPUI using the native event-loop architecture for this OS. */
  init(options?: WindowOptions | undefined | null): void
  /**
   * Apply a batch of mutations in a single FFI call.
   *
   * Accepts a JSON array of mutation tuples. Each tuple is an array where
   * the first element is the operation name (string) and remaining elements
   * are the arguments:
   *
   *   ["createElement",    id, "type"]
   *   ["destroyElement",   id]
   *   ["appendChild",      parentId, childId]
   *   ["insertBefore",     parentId, childId, beforeId]
   *   ["setStyle",         id, { ...style }]
   *   ["setText",          id, "content"]
   *   ["setEventListener", id, "eventType", true|false]
   *   ["setRoot",          id]
   *   ["setCustomProp",    id, "key", value]
   *
   * Returns accumulated destroyed IDs from all destroyElement ops.
   * Acquires the tree mutex ONCE for the entire batch.
   */
  applyBatch(json: string): Array<number>
  /** Pump the native event loop. Returns false after the last window closes. */
  tick(): boolean
  isInitialized(): boolean
  /**
   * Whether JavaScript must call tick() until it returns false.
   *
   * macOS: tick() pumps AppKit. Windows/Linux: tick() only reports whether
   * the UI thread is still inside `Platform::run`. Both return false after
   * the last window closes so the JS frame loop can exit the process.
   */
  requiresTick(): boolean
  /**
   * The paintable size of the window in logical pixels, excluding any
   * platform title bar. This used to answer a hardcoded 800x600, so anything
   * that turned a mouse position into layout coordinates pointed at the
   * wrong place on every window that was not exactly that size.
   */
  getWindowSize(): WindowSize
  getWindowInsets(): WindowInsets
  /** `"hidden"` | `"minimal"` | `"full"`. Paints into the scene after layout. */
  setDebugFrameOverlay(mode: string): string
  /** Hidden → minimal → full → hidden. */
  cycleDebugFrameOverlay(): string
  getDebugFrameOverlay(): string
  /** Clears the last 1000 draw samples. Frame count stays. */
  resetDebugFrameOverlayStats(): void
  /** Same numbers as the on-screen overlay: current, p90, p99, max, frames. */
  getDebugFrameOverlayStats(): DebugFrameOverlayStats
  /**
   * Bring the window forward and give it focus. This is how a window opened
   * with `show: false` or `focus: false` is revealed later.
   */
  activateWindow(): void
  setWindowTitle(title: string): void
  focusElement(elementId: number): void
  /** Move focus to the next GPUI tab stop. */
  focusNext(): void
  /** Move focus to the previous GPUI tab stop. */
  focusPrevious(): void
  /** Enable the window key events requested by the React renderer. */
  setWindowKeyEvents(keyDown: boolean, keyUp: boolean, eventId: number): void
  blur(): void
  /** The current text selection joined in document order, or null. */
  getSelectedText(): string | null
  /** Drop the current selection and request a repaint. */
  clearSelection(): void
  /**
   * Set the scroll offset of a scrollable element.
   * x and y are negative pixel values (scroll down = more negative y).
   */
  scrollTo(elementId: number, x: number, y: number): void
  /**
   * Scroll a child into view by its index in the children list.
   *
   * For a `<virtual-list>` the scroll is queued and applied on the next
   * render, after that frame's child splice, so indices computed against a
   * just-committed child list are never shifted twice. `offsetInItem` is in
   * pixels and may be negative, which anchors the viewport top above the
   * item and resolves against measured heights at layout time.
   */
  scrollToItem(elementId: number, index: number, offsetInItem?: number | undefined | null): void
  /**
   * The logical scroll anchor of a `<virtual-list>`:
   * `[itemIndex, offsetInItemPx, viewportHeightPx]`, or null for anything
   * else. `itemIndex == item count` is gpui's at-end sentinel.
   *
   * Unlike `getScrollOffset` this is exact even while row heights are still
   * estimates, because it is the anchor gpui itself scrolls by.
   */
  getListScrollTop(elementId: number): Array<number> | null
  /**
   * Get the current scroll offset of a scrollable element.
   * Returns [x, y] or null if the element has no scroll handle.
   */
  getScrollOffset(elementId: number): Array<number> | null
  getAutomationTree(): string
  getElementBounds(id: number): Array<number> | null
  getAllText(): Array<string>
  getPaintedText(): Array<string>
  /**
   * Every highlight wash painted in the last frame, in paint order.
   *
   * A quad is invisible to `getPaintedText()`, so this is the only way to
   * assert on `highlight` without a screenshot.
   */
  getPaintedHighlights(): Array<HighlightMatch>
  /** Simulate space-separated keystrokes through the focused element's input pipeline. */
  simulateKeystrokes(keystrokes: string): void
  simulateKeyDown(keystroke: string, isHeld?: boolean | undefined | null): void
  simulateKeyUp(keystroke: string): void
  /** `modifiers` uses the `press()` syntax: "cmd", "cmd-shift", "alt". */
  simulateClick(x: number, y: number, button?: number | undefined | null, modifiers?: string | undefined | null): void
  simulateMouseDown(x: number, y: number, button?: number | undefined | null, modifiers?: string | undefined | null): void
  simulateMouseUp(x: number, y: number, button?: number | undefined | null, modifiers?: string | undefined | null): void
  simulateMouseMove(x: number, y: number, pressedButton?: number | undefined | null, modifiers?: string | undefined | null): void
  /**
   * Dispatch a wheel event through the same GPUI hit test the trackpad uses.
   * Deltas are pixels: negative `delta_y` scrolls down, negative `delta_x`
   * pans right, matching `TestGpuixRenderer::simulate_scroll_wheel`.
   */
  simulateScrollWheel(x: number, y: number, deltaX: number, deltaY: number, modifiers?: string | undefined | null): void
  clockPause(): number
  clockSet(nowMs: number): number
  clockFastForward(deltaMs: number): number
  clockResume(): number
  captureScreenshot(path: string): void
}

/**
 * GPU-backed GPUI test renderer. Uses VisualTestAppContext with the native
 * Metal or DirectX renderer and TestDispatcher for deterministic scheduling.
 * Same GpuixView and rendering pipeline as production.
 *
 * Usage from JS:
 *   const r = new TestGpuixRenderer()
 *   r.applyBatch('[["createElement",1,"div"],["setRoot",1]]')
 *   r.flush()                  // triggers GpuixView::render() on the GPU
 *   r.simulateClick(50, 50)    // dispatches through GPUI hit testing
 *   const events = r.drainEvents()
 *   r.captureScreenshot("/tmp/test.png")  // saves rendered UI as PNG
 */
export declare class TestGpuixRenderer {
  constructor(width?: number | undefined | null, height?: number | undefined | null)
  /**
   * How many elements the retained tree holds, reachable from the root or
   * not. `getTreeJson` walks from the root, so it cannot see a node that was
   * detached and never destroyed. This is the only way a test can prove a
   * removal actually freed it.
   */
  getRetainedElementCount(): number
  /**
   * Apply a batch of mutations in a single FFI call.
   * Same format as GpuixRenderer::apply_batch (string op names).
   * Returns accumulated destroyed IDs from all destroyElement ops.
   */
  applyBatch(json: string): Array<number>
  /**
   * Notify the view entity and run GPUI until parked.
   * This triggers GpuixView::render() → build_element() → GPUI layout.
   * Must be called after mutations and before simulating events (GPUI's
   * hit testing requires elements to be laid out).
   */
  flush(): void
  /**
   * Simulate a click at the given window coordinates.
   * Dispatches MouseDown + MouseUp through GPUI's input pipeline,
   * which triggers the same event handlers as production.
   * IMPORTANT: Call flush() before this — hit testing requires laid-out elements.
   * `modifiers` uses the `press()` syntax: "cmd", "cmd-shift", "alt".
   */
  simulateClick(x: number, y: number, button?: number | undefined | null, modifiers?: string | undefined | null): void
  /**
   * Simulate key strokes through GPUI's input pipeline.
   * Format: space-separated keys, e.g. "a", "enter", "cmd-shift-p".
   * The focused element receives keyDown/keyUp events.
   */
  simulateKeystrokes(keystrokes: string): void
  /**
   * Simulate a single key down event through GPUI's input pipeline.
   * Format: modifier-key string, e.g. "a", "enter", "cmd-s".
   * Unlike simulate_keystrokes, this dispatches ONLY a KeyDownEvent —
   * no automatic KeyUpEvent follows. Use with simulate_key_up for
   * fine-grained key event testing.
   */
  simulateKeyDown(keystroke: string, isHeld?: boolean | undefined | null): void
  /**
   * Simulate a single key up event through GPUI's input pipeline.
   * Format: modifier-key string, e.g. "a", "enter", "cmd-s".
   * Pairs with simulate_key_down for fine-grained key event testing.
   */
  simulateKeyUp(keystroke: string): void
  /**
   * Simulate a mouse move to the given coordinates.
   * pressed_button: optional mouse button held during move (0=left, 1=middle, 2=right).
   * Used to simulate drag events.
   */
  simulateMouseMove(x: number, y: number, pressedButton?: number | undefined | null, modifiers?: string | undefined | null): void
  /**
   * Focus an element by its numeric ID.
   * The element must have a FocusHandle (created by sync_focus_handles when
   * the element has keyDown, keyUp, focus, or blur listeners).
   * Call flush() before this so the element tree and focus handles exist.
   */
  focusElement(id: number): void
  focusNext(): void
  focusPrevious(): void
  setWindowKeyEvents(keyDown: boolean, keyUp: boolean, eventId: number): void
  /**
   * Simulate a mouse down event at the given window coordinates.
   * Button: 0=left, 1=middle, 2=right. Defaults to left (0).
   */
  simulateMouseDown(x: number, y: number, button?: number | undefined | null, modifiers?: string | undefined | null): void
  /**
   * Simulate a mouse up event at the given window coordinates.
   * Button: 0=left, 1=middle, 2=right. Defaults to left (0).
   */
  simulateMouseUp(x: number, y: number, button?: number | undefined | null, modifiers?: string | undefined | null): void
  /**
   * Simulate a scroll wheel event at the given position.
   * delta_x and delta_y are in pixels (negative = scroll up/left).
   */
  simulateScrollWheel(x: number, y: number, deltaX: number, deltaY: number, modifiers?: string | undefined | null): void
  /** The current text selection joined in document order, or null. */
  getSelectedText(): string | null
  /** Drop the current selection. */
  clearSelection(): void
  /**
   * Syntax-cache counters as `[hits, misses, documents]`.
   *
   * GPUIX rebuilds its whole element tree every frame, so a `<code>` block
   * that misses the cache reparses at frame rate. A test can watch the hit
   * count to catch that regression before a profiler does.
   */
  getSyntaxCacheStats(): Array<number>
  /**
   * Every string painted in the last frame, in paint order.
   *
   * `getAllText()` only sees `<text>` nodes in the retained tree. Native
   * elements such as `<code>` and `<diff>` draw their text inside gpui, so
   * this is the only way to assert on what they actually rendered.
   */
  getPaintedText(): Array<string>
  /**
   * Every highlight wash painted in the last frame, in paint order.
   *
   * A quad is invisible to `getPaintedText()`, so this is the only way to
   * assert on `highlight` without a screenshot. Each entry carries its rects,
   * so a soft-wrapped match is provably two boxes.
   */
  getPaintedHighlights(): Array<HighlightMatch>
  /**
   * Drag-select from one point to another: mouse down, move, up.
   *
   * A single helper rather than three calls because the listeners that drive
   * selection are registered during **paint**, so a flush must sit between
   * the down and the move. Getting that order wrong silently selects nothing,
   * which is a miserable thing to debug from JS.
   */
  dragSelect(x1: number, y1: number, x2: number, y2: number): void
  /**
   * Set the scroll offset of a scrollable element.
   * x and y are negative pixel values (scroll down = more negative y).
   * Call flush() after to apply the offset and re-render.
   */
  scrollTo(elementId: number, x: number, y: number): void
  /**
   * Scroll a child into view by its index in the children list.
   * Call flush() after to apply and re-render. For a `<virtual-list>` the
   * scroll is queued and applied on that flush, after the child splice.
   * `offset_in_item` is in pixels and may be negative, which anchors the
   * viewport top above the item.
   */
  scrollToItem(elementId: number, index: number, offsetInItem?: number | undefined | null): void
  /**
   * The logical scroll anchor of a `<virtual-list>`:
   * `[itemIndex, offsetInItemPx, viewportHeightPx]`, or null for anything
   * else. `itemIndex == item count` is gpui's at-end sentinel.
   */
  getListScrollTop(elementId: number): Array<number> | null
  /** `"hidden"` | `"minimal"` | `"full"`. */
  setDebugFrameOverlay(mode: string): string
  /** Hidden → minimal → full → hidden. */
  cycleDebugFrameOverlay(): string
  getDebugFrameOverlay(): string
  /** Clears the last 1000 draw samples. Frame count stays. */
  resetDebugFrameOverlayStats(): void
  /** Same numbers as the on-screen overlay: current, p90, p99, max, frames. */
  getDebugFrameOverlayStats(): DebugFrameOverlayStats
  /**
   * Get the current scroll offset of a scrollable element.
   * Returns [x, y] or null if the element has no scroll handle.
   */
  getScrollOffset(elementId: number): Array<number> | null
  /**
   * Capture a screenshot of the current rendered state and save as PNG.
   * Supported on macOS through Metal and Windows through DirectX.
   */
  captureScreenshot(path: string): void
  /**
   * Return and clear all collected events since the last drain.
   * Events are collected synchronously — no event loop queuing.
   */
  drainEvents(): Array<EventPayload>
  /** Get all text content in the tree (depth-first order). */
  getAllText(): Array<string>
  /** Find element IDs matching the given type (e.g. "div", "text"). */
  findByType(elementType: string): Array<number>
  /** Check if an element has a specific event listener. */
  hasEventListener(id: number, eventType: string): boolean
  /** Get the text content of an element. */
  getText(id: number): string | null
  /** Get the full tree as JSON for snapshot testing. */
  getTreeJson(): string
  /** Tree JSON with last-paint bounds. Used by the automation locators. */
  getAutomationTree(): string
  /** Last painted bounds for an element, or null if it was not painted. */
  getElementBounds(id: number): Array<number> | null
  clockPause(): number
  clockSet(nowMs: number): number
  clockFastForward(deltaMs: number): number
  clockResume(): number
  /** Advance GPUI's deterministic test executor and run due timers. */
  advanceTime(milliseconds: number): void
  /** Get the root element ID, or null if no root is set. */
  getRootId(): number | null
  /**
   * The offscreen window size, so `useWindowSize()` reports the same numbers
   * under test as in a real window instead of falling back to a default.
   */
  getWindowSize(): WindowSize
}

/** Recorded draw times from the debug frame overlay. */
export interface DebugFrameOverlayStats {
  currentMs?: number
  p90Ms?: number
  p99Ms?: number
  maxMs?: number
  frames: number
  samples: number
}

export interface EdgeInsets {
  top: number
  right: number
  bottom: number
  left: number
}

export interface EventModifiers {
  shift: boolean
  ctrl: boolean
  alt: boolean
  cmd: boolean
}

/** Event payload sent back to JS when a user interacts with an element. */
export interface EventPayload {
  /** Numeric element ID (matches the ID assigned in JS via createElement). */
  elementId: number
  /**
   * Event type string — matches the key used in EVENT_PROPS on the JS side.
   * e.g. "click", "mouseDown", "mouseEnter", "keyDown", "scroll", etc.
   */
  eventType: string
  /** Mouse X position in window coordinates (pixels). */
  x?: number
  /** Mouse Y position in window coordinates (pixels). */
  y?: number
  /**
   * Which mouse button: 0=left, 1=middle, 2=right.
   * Populated for: mouseDown, mouseUp, click, mouseDownOutside, contextMenu.
   */
  button?: number
  /**
   * Number of consecutive clicks (1=single, 2=double, 3=triple).
   * Populated for: mouseDown, mouseUp, click.
   */
  clickCount?: number
  /**
   * Whether this is a right-click (convenience for click events).
   * true when button==2 or ClickEvent::is_right_click().
   */
  isRightClick?: boolean
  /**
   * Which mouse button is currently held during a mouseMove.
   * Same encoding as `button`: 0=left, 1=middle, 2=right.
   * Populated for: mouseMove.
   */
  pressedButton?: number
  /**
   * Key name, e.g. "a", "enter", "escape", "down", "left", "f1".
   * Populated for: keyDown, keyUp.
   */
  key?: string
  /**
   * The character produced by the key press (e.g. "ß" for option-s).
   * May differ from `key` when modifiers are active.
   * Populated for: keyDown, keyUp.
   */
  keyChar?: string
  /**
   * Whether this is a key-repeat event (key held down).
   * Populated for: keyDown.
   */
  isHeld?: boolean
  /**
   * Scroll delta on the X axis (pixels or lines, see `precise`).
   * Populated for: scroll.
   */
  deltaX?: number
  /**
   * Scroll delta on the Y axis (pixels or lines, see `precise`).
   * Populated for: scroll.
   */
  deltaY?: number
  /**
   * true = pixel-precise (trackpad), false = line-based (mouse wheel).
   * Populated for: scroll.
   */
  precise?: boolean
  /**
   * Touch phase for scroll: "started", "moved", "ended".
   * Populated for: scroll (trackpad gestures).
   */
  touchPhase?: string
  /**
   * true = mouse entered element, false = mouse left element.
   * Populated for: mouseEnter, mouseLeave.
   */
  hovered?: boolean
  /**
   * Element-defined string payload.
   * Populated for: `<diff>` toggleFile (the file path), showMore (the
   * hidden line count), and lineClick (the line text); `<markdown>`
   * linkClick (the URL).
   */
  value?: string
  /** Line number on the pre-change side. Populated for: `<diff>` lineClick. */
  oldLine?: number
  /** Line number on the post-change side. Populated for: `<diff>` lineClick. */
  newLine?: number
  /** First visible logical index. Populated for: `<virtual-list>` visibleRange. */
  startIndex?: number
  /** Exclusive end of the visible logical range. Populated for: visibleRange. */
  endIndex?: number
  /**
   * Matches found by this element's `highlight` prop. Counted once per match
   * even when it is split across several painted runs, and it counts every
   * retained match, not only the ones currently on screen.
   * Populated for: highlight.
   */
  matchCount?: number
  modifiers?: EventModifiers
}

/** True only when this binary compiled the real GPU test renderer. */
export declare function hasTestGpuixRenderer(): boolean

/**
 * One highlight wash painted in the last frame, with the boxes it drew.
 *
 * The rects matter: a quad never lands in `getPaintedText()`, and a match that
 * soft-wraps must produce one box per visual row. Without the geometry the only
 * way to assert either is a screenshot.
 */
export interface HighlightMatch {
  /** Numeric id of the element that painted the run. */
  elementId: number
  /** Index of the run within that element. 0 for a plain `<text>`. */
  sub: number
  /** The full string of the run, so `text.slice(start, end)` is the match. */
  text: string
  /** UTF-16 code-unit offsets into `text`, the units JS strings use. */
  start: number
  end: number
  active: boolean
  rects: Array<HighlightRect>
}

export interface HighlightRect {
  x: number
  y: number
  width: number
  height: number
}

export interface WindowInsets {
  safeArea: EdgeInsets
  ime: EdgeInsets
  effective: EdgeInsets
}

export interface WindowOptions {
  title?: string
  /**
   * The name used inside the macOS "Hide" and "Quit" menu items. Defaults to
   * `title`. It does NOT set the title of the application menu itself: macOS
   * takes that from the executable, and only a `.app` bundle changes it.
   */
  appName?: string
  width?: number
  height?: number
  minWidth?: number
  minHeight?: number
  resizable?: boolean
  fullscreen?: boolean
  /** Plain alpha transparency. Prefer `window_background` when you need blur. */
  transparent?: boolean
  /** Hide the native titlebar so the app can draw chrome under the traffic lights. */
  titlebarTransparent?: boolean
  /**
   * `"opaque"` | `"transparent"` | `"blurred"`. `transparent: true` is the
   * same as `"transparent"` when this is unset.
   */
  windowBackground?: string
  trafficLightX?: number
  trafficLightY?: number
  /**
   * Give the window key focus when it opens. `false` opens it behind the
   * active app, like `open -g`. Ignored on Linux.
   */
  focus?: boolean
  /**
   * Show the window when it opens. `false` opens it hidden; call
   * `activateWindow()` to reveal it. Ignored on Linux.
   */
  show?: boolean
}

export interface WindowSize {
  width: number
  height: number
}
/**
 * Spawn a terminal session: PTY + model + pool registration. Resolves with
 * the sessionId that `<terminal sessionId>` binds to.
 *
 * Synchronous on purpose: the test path (run_on_test_app) needs this-thread
 * access to VisualTestState (thread_local), and napi async fns run on the
 * tokio runtime — a different thread. The JS seam keeps its Promise shape
 * via a thin async wrapper at the injection site (main.tsx / e2e).
 */
export declare function createTerminalSession(opts?: SpawnOptionsJs | undefined | null): number

/**
 * Destroy a session: kill the PTY child, drop the model, remove from the
 * pool. Views still bound to it render the placeholder afterwards.
 */
export declare function destroyTerminalSession(sessionId: number): void

/**
 * Register the `<terminal>` element factory with GPUIX. Must run before the
 * renderer is initialized (`main.tsx` calls it at startup, before
 * `renderer.init()`); idempotent (a second call just re-registers the type).
 */
export declare function installTerminalElement(): void

/**
 * Register the global session-event callback (once, at app startup).
 * TSF protocol: `cb(null, e)` — the payload is the SECOND argument
 * (first is the error slot). In JS: `onSessionEvent((_err, e) => ...)`.
 */
export declare function onSessionEvent(cb: (err: null, e: import('./index').SessionEvent) => void): void

/**
 * Global session event payload (R2): one channel for title/bell/exit,
 * delivered even when the element is unmounted (background PTY).
 */
export interface SessionEvent {
  type: string
  sessionId: number
  title?: string
  code?: number
}

/**
 * Mirror of `SpawnOptions` (Rust) — see architecture.md §2.3. Appearance
 * settings do NOT belong here: they are element props, applied live.
 */
export interface SpawnOptionsJs {
  cwd?: string
  program?: string
  args?: Array<string>
  env?: Record<string, string>
  initCommand?: string
  scrollbackLines?: number
}
