/* auto-generated by NAPI-RS */
/* eslint-disable */
/** The main GPUI renderer exposed to Node.js. */
export declare class GpuixRenderer {
  constructor(eventCallback?: (((err: Error | null, arg: EventPayload) => any)) | undefined | null)
  /** Initialize GPUI using the native event-loop architecture for this OS. */
  init(options?: WindowOptions | undefined | null): void
  /**
   * Apply a batch of mutations in a single FFI call.
   *
   * Accepts a JSON array of mutation tuples. Each tuple is an array where
   * the first element is the operation name (string) and remaining elements
   * are the arguments:
   *
   *   ["createElement",    id, "type"]
   *   ["destroyElement",   id]
   *   ["appendChild",      parentId, childId]
   *   ["insertBefore",     parentId, childId, beforeId]
   *   ["setStyle",         id, { ...style }]
   *   ["setText",          id, "content"]
   *   ["setEventListener", id, "eventType", true|false]
   *   ["setRoot",          id]
   *   ["setCustomProp",    id, "key", value]
   *
   * Returns accumulated destroyed IDs from all destroyElement ops.
   * Acquires the tree mutex ONCE for the entire batch.
   */
  applyBatch(json: string): Array<number>
  /** Pump the native event loop. Returns false after the last window closes. */
  tick(): boolean
  isInitialized(): boolean
  /**
   * Whether JavaScript must call tick() until it returns false.
   *
   * macOS: tick() pumps AppKit. Windows/Linux: tick() only reports whether
   * the UI thread is still inside `Platform::run`. Both return false after
   * the last window closes so the JS frame loop can exit the process.
   */
  requiresTick(): boolean
  /**
   * The paintable size of the window in logical pixels, excluding any
   * platform title bar. This used to answer a hardcoded 800x600, so anything
   * that turned a mouse position into layout coordinates pointed at the
   * wrong place on every window that was not exactly that size.
   */
  getWindowSize(): WindowSize
  getWindowInsets(): WindowInsets
  /** `"hidden"` | `"minimal"` | `"full"`. Paints into the scene after layout. */
  setDebugFrameOverlay(mode: string): string
  /** Hidden → minimal → full → hidden. */
  cycleDebugFrameOverlay(): string
  getDebugFrameOverlay(): string
  /** Clears the last 1000 draw samples. Frame count stays. */
  resetDebugFrameOverlayStats(): void
  /** Same numbers as the on-screen overlay: current, p90, p99, max, frames. */
  getDebugFrameOverlayStats(): DebugFrameOverlayStats
  /**
   * Bring the window forward and give it focus. This is how a window opened
   * with `show: false` or `focus: false` is revealed later.
   */
  activateWindow(): void
  setWindowTitle(title: string): void
  /**
   * Begin a user-driven window move from the current pointer position —
   * the custom title bar's drag gesture on macOS and Linux (call from a
   * mouse-move handler after a mouse-down on the drag region). On Windows
   * this is not needed: dragging is handled by the OS through
   * `windowControlArea: "drag"` hit-testing.
   */
  startWindowMove(): void
  /**
   * Respond to a double click on the custom-drawn title bar: macOS zooms
   * per the system preference, other platforms toggle maximize.
   */
  titlebarDoubleClick(): void
  /** Minimize the window (Linux CSD caption button; also usable elsewhere). */
  minimizeWindow(): void
  /** Close the window (Linux CSD caption button). */
  closeWindow(): void
  focusElement(elementId: number): void
  /** Move focus to the next GPUI tab stop. */
  focusNext(): void
  /** Move focus to the previous GPUI tab stop. */
  focusPrevious(): void
  /** Enable the window key events requested by the React renderer. */
  setWindowKeyEvents(keyDown: boolean, keyUp: boolean, eventId: number): void
  blur(): void
  /** The current text selection joined in document order, or null. */
  getSelectedText(): string | null
  /** Drop the current selection and request a repaint. */
  clearSelection(): void
  /**
   * Set the scroll offset of a scrollable element.
   * x and y are negative pixel values (scroll down = more negative y).
   */
  scrollTo(elementId: number, x: number, y: number): void
  /**
   * Scroll a child into view by its index in the children list.
   *
   * For a `<virtual-list>` the scroll is queued and applied on the next
   * render, after that frame's child splice, so indices computed against a
   * just-committed child list are never shifted twice. `offsetInItem` is in
   * pixels and may be negative, which anchors the viewport top above the
   * item and resolves against measured heights at layout time.
   */
  scrollToItem(elementId: number, index: number, offsetInItem?: number | undefined | null): void
  /**
   * The logical scroll anchor of a `<virtual-list>`:
   * `[itemIndex, offsetInItemPx, viewportHeightPx]`, or null for anything
   * else. `itemIndex == item count` is gpui's at-end sentinel.
   *
   * Unlike `getScrollOffset` this is exact even while row heights are still
   * estimates, because it is the anchor gpui itself scrolls by.
   */
  getListScrollTop(elementId: number): Array<number> | null
  /**
   * Get the current scroll offset of a scrollable element.
   * Returns [x, y] or null if the element has no scroll handle.
   */
  getScrollOffset(elementId: number): Array<number> | null
  getAutomationTree(): string
  getElementBounds(id: number): Array<number> | null
  getAllText(): Array<string>
  getPaintedText(): Array<string>
  /**
   * Every highlight wash painted in the last frame, in paint order.
   *
   * A quad is invisible to `getPaintedText()`, so this is the only way to
   * assert on `highlight` without a screenshot.
   */
  getPaintedHighlights(): Array<HighlightMatch>
  /** Simulate space-separated keystrokes through the focused element's input pipeline. */
  simulateKeystrokes(keystrokes: string): void
  simulateKeyDown(keystroke: string, isHeld?: boolean | undefined | null): void
  simulateKeyUp(keystroke: string): void
  /** `modifiers` uses the `press()` syntax: "cmd", "cmd-shift", "alt". */
  simulateClick(x: number, y: number, button?: number | undefined | null, modifiers?: string | undefined | null): void
  simulateMouseDown(x: number, y: number, button?: number | undefined | null, modifiers?: string | undefined | null): void
  simulateMouseUp(x: number, y: number, button?: number | undefined | null, modifiers?: string | undefined | null): void
  simulateMouseMove(x: number, y: number, pressedButton?: number | undefined | null, modifiers?: string | undefined | null): void
  /**
   * Dispatch a wheel event through the same GPUI hit test the trackpad uses.
   * Deltas are pixels: negative `delta_y` scrolls down, negative `delta_x`
   * pans right, matching `TestGpuixRenderer::simulate_scroll_wheel`.
   */
  simulateScrollWheel(x: number, y: number, deltaX: number, deltaY: number, modifiers?: string | undefined | null): void
  clockPause(): number
  clockSet(nowMs: number): number
  clockFastForward(deltaMs: number): number
  clockResume(): number
  captureScreenshot(path: string): void
}

export declare class TestGpuixRenderer {
  constructor(width?: number | undefined | null, height?: number | undefined | null)
}

/** Recorded draw times from the debug frame overlay. */
export interface DebugFrameOverlayStats {
  currentMs?: number
  p90Ms?: number
  p99Ms?: number
  maxMs?: number
  frames: number
  samples: number
}

export interface EdgeInsets {
  top: number
  right: number
  bottom: number
  left: number
}

export interface EventModifiers {
  shift: boolean
  ctrl: boolean
  alt: boolean
  cmd: boolean
}

/** Event payload sent back to JS when a user interacts with an element. */
export interface EventPayload {
  /** Numeric element ID (matches the ID assigned in JS via createElement). */
  elementId: number
  /**
   * Event type string — matches the key used in EVENT_PROPS on the JS side.
   * e.g. "click", "mouseDown", "mouseEnter", "keyDown", "scroll", etc.
   */
  eventType: string
  /** Mouse X position in window coordinates (pixels). */
  x?: number
  /** Mouse Y position in window coordinates (pixels). */
  y?: number
  /**
   * Which mouse button: 0=left, 1=middle, 2=right.
   * Populated for: mouseDown, mouseUp, click, mouseDownOutside, contextMenu.
   */
  button?: number
  /**
   * Number of consecutive clicks (1=single, 2=double, 3=triple).
   * Populated for: mouseDown, mouseUp, click.
   */
  clickCount?: number
  /**
   * Whether this is a right-click (convenience for click events).
   * true when button==2 or ClickEvent::is_right_click().
   */
  isRightClick?: boolean
  /**
   * Which mouse button is currently held during a mouseMove.
   * Same encoding as `button`: 0=left, 1=middle, 2=right.
   * Populated for: mouseMove.
   */
  pressedButton?: number
  /**
   * Key name, e.g. "a", "enter", "escape", "down", "left", "f1".
   * Populated for: keyDown, keyUp.
   */
  key?: string
  /**
   * The character produced by the key press (e.g. "ß" for option-s).
   * May differ from `key` when modifiers are active.
   * Populated for: keyDown, keyUp.
   */
  keyChar?: string
  /**
   * Whether this is a key-repeat event (key held down).
   * Populated for: keyDown.
   */
  isHeld?: boolean
  /**
   * Scroll delta on the X axis (pixels or lines, see `precise`).
   * Populated for: scroll.
   */
  deltaX?: number
  /**
   * Scroll delta on the Y axis (pixels or lines, see `precise`).
   * Populated for: scroll.
   */
  deltaY?: number
  /**
   * true = pixel-precise (trackpad), false = line-based (mouse wheel).
   * Populated for: scroll.
   */
  precise?: boolean
  /**
   * Touch phase for scroll: "started", "moved", "ended".
   * Populated for: scroll (trackpad gestures).
   */
  touchPhase?: string
  /**
   * true = mouse entered element, false = mouse left element.
   * Populated for: mouseEnter, mouseLeave.
   */
  hovered?: boolean
  /**
   * Element-defined string payload.
   * Populated for: `<diff>` toggleFile (the file path), showMore (the
   * hidden line count), and lineClick (the line text); `<markdown>`
   * linkClick (the URL).
   */
  value?: string
  /** Line number on the pre-change side. Populated for: `<diff>` lineClick. */
  oldLine?: number
  /** Line number on the post-change side. Populated for: `<diff>` lineClick. */
  newLine?: number
  /** First visible logical index. Populated for: `<virtual-list>` visibleRange. */
  startIndex?: number
  /** Exclusive end of the visible logical range. Populated for: visibleRange. */
  endIndex?: number
  /**
   * Matches found by this element's `highlight` prop. Counted once per match
   * even when it is split across several painted runs, and it counts every
   * retained match, not only the ones currently on screen.
   * Populated for: highlight.
   */
  matchCount?: number
  modifiers?: EventModifiers
}

/** True only when this binary compiled the real GPU test renderer. */
export declare function hasTestGpuixRenderer(): boolean

/**
 * One highlight wash painted in the last frame, with the boxes it drew.
 *
 * The rects matter: a quad never lands in `getPaintedText()`, and a match that
 * soft-wraps must produce one box per visual row. Without the geometry the only
 * way to assert either is a screenshot.
 */
export interface HighlightMatch {
  /** Numeric id of the element that painted the run. */
  elementId: number
  /** Index of the run within that element. 0 for a plain `<text>`. */
  sub: number
  /** The full string of the run, so `text.slice(start, end)` is the match. */
  text: string
  /** UTF-16 code-unit offsets into `text`, the units JS strings use. */
  start: number
  end: number
  active: boolean
  rects: Array<HighlightRect>
}

export interface HighlightRect {
  x: number
  y: number
  width: number
  height: number
}

export interface WindowInsets {
  safeArea: EdgeInsets
  ime: EdgeInsets
  effective: EdgeInsets
}

export interface WindowOptions {
  title?: string
  /**
   * The name used inside the macOS "Hide" and "Quit" menu items. Defaults to
   * `title`. It does NOT set the title of the application menu itself: macOS
   * takes that from the executable, and only a `.app` bundle changes it.
   */
  appName?: string
  width?: number
  height?: number
  minWidth?: number
  minHeight?: number
  resizable?: boolean
  fullscreen?: boolean
  /** Plain alpha transparency. Prefer `window_background` when you need blur. */
  transparent?: boolean
  /** Hide the native titlebar so the app can draw chrome under the traffic lights. */
  titlebarTransparent?: boolean
  /**
   * `"client"` | `"server"`. Linux/X11/Wayland window decorations. Client
   * asks the WM to omit its title bar so the app can draw CSD chrome.
   * Ignored on macOS/Windows. Defaults to server-side decorations.
   */
  windowDecorations?: string
  /**
   * `"opaque"` | `"transparent"` | `"blurred"`. `transparent: true` is the
   * same as `"transparent"` when this is unset.
   */
  windowBackground?: string
  trafficLightX?: number
  trafficLightY?: number
  /**
   * Give the window key focus when it opens. `false` opens it behind the
   * active app, like `open -g`. Ignored on Linux.
   */
  focus?: boolean
  /**
   * Show the window when it opens. `false` opens it hidden; call
   * `activateWindow()` to reveal it. Ignored on Linux.
   */
  show?: boolean
}

export interface WindowSize {
  width: number
  height: number
}
/**
 * Match native window chrome to the dark UI (Zed `init_app_appearance`).
 * On macOS this sets `GPUIApplication.appearance` to DarkAqua so traffic-light
 * glyphs use the dark-theme artwork. Prefer letting `renderer.init` do this
 * (after GPUIApplication exists, before the first NSWindow). Calling the
 * stock `NSApplication` class first freezes the AppKit singleton.
 * A no-op on platforms without the override.
 */
export declare function applyWindowAppearance(): void

/**
 * Spawn a terminal session: PTY + model + pool registration. Resolves with
 * the sessionId that `<terminal sessionId>` binds to.
 *
 * Synchronous on purpose: the test path (run_on_test_app) needs this-thread
 * access to VisualTestState (thread_local), and napi async fns run on the
 * tokio runtime — a different thread. The JS seam keeps its Promise shape
 * via a thin async wrapper at the injection site (main.tsx / e2e).
 */
export declare function createTerminalSession(opts?: SpawnOptionsJs | undefined | null): number

/**
 * Destroy a session: kill the PTY child, drop the model, remove from the
 * pool. Views still bound to it render the placeholder afterwards.
 */
export declare function destroyTerminalSession(sessionId: number): void

/**
 * Register the `<terminal>` element factory with GPUIX. Must run before the
 * renderer is initialized (`main.tsx` calls it at startup, before
 * `renderer.init()`). A second call currently pushes another factory; the
 * first `GpuixView` still drains the global table (gpuix 0002).
 */
export declare function installTerminalElement(): void

/**
 * Show a desktop toast (Windows). Fire-and-forget on a detached thread:
 * failures log to stderr and never reject — notifications are a
 * non-critical path (bell → notify, settings.desktop gates the call).
 */
export declare function notifyDesktop(title: string, body: string, sound: boolean): void

/**
 * Register the global session-event callback (once, at app startup).
 * TSF protocol: `cb(null, e)` — the payload is the SECOND argument
 * (first is the error slot). In JS: `onSessionEvent((_err, e) => ...)`.
 */
export declare function onSessionEvent(cb: (err: null, e: import('./index').SessionEvent) => void): void

/**
 * Native folder picker (W3). Callback contract mirrors `onSessionEvent`:
 * payload is the SECOND argument — `pickDirectory((_err, path) => ...)`.
 * `path === null` = cancelled / unavailable. On macOS the modal loop runs
 * synchronously on the JS/main thread (the panel pumps AppKit); on Windows
 * it runs on a detached STA thread. The JS side treats this as async (the
 * callback may fire on a later tick in both cases).
 */
export declare function pickDirectory(cb: (err: null, path: string | null) => void): void

/**
 * Global session event payload (R2): one channel for title/bell/exit,
 * delivered even when the element is unmounted (background PTY).
 */
export interface SessionEvent {
  type: string
  sessionId: number
  title?: string
  code?: number
}

/**
 * Mirror of `SpawnOptions` (Rust) — see architecture.md §2.3. Appearance
 * settings do NOT belong here: they are element props, applied live.
 */
export interface SpawnOptionsJs {
  cwd?: string
  program?: string
  args?: Array<string>
  env?: Record<string, string>
  initCommand?: string
  scrollbackLines?: number
}
